/**
 * Quotes and convictions distilled from the user's writings
 * (worldview, philosophical core, and personal principles).
 */
export const USER_CONVICTIONS = [
  "NO MAN RUNS BEHIND MOTIVATION. THEY ARE FUELED BY RESPONSIBILITY AND PURPOSE.",
  "HUMANS ARE NOT 'SOCIAL BEINGS' — THEY ARE MEGALOMANIACS.",
  "EGO IS THE BIGGEST ASSET IN A MAN'S JOURNEY.",
  "INNOVATION HAS NO ROOM IN THE BRAINS OF TODAY.",
  "THE ONLY WAY TO CORRECT THE WORLD IS TO CORRECT YOURSELF.",
  "THE PROBABILITY OF SAVING THIS GENERATION IS MATHEMATICALLY NEGLIGIBLE.",
  "LOVE IS NOTHING BUT BEING PARTIAL — CREATING A DIFFERENCE IN REALITY.",
  "LOVE IS A PATH, NOT A DESTINATION. LOVE LEADS TO ANOTHER DOOR: GRIEF.",
  "THE BETTER SELF IS ALWAYS THE CURRENT YOU.",
  "REFLECTION WITHOUT THE WILL TO ACT DIFFERENTLY IS SELF-ABSORPTION.",
  "LIFE ITSELF IS A WAR OF INFLUENCE.",
  "KNOWING WHAT YOU CAN BE AND STILL NOT DOING WHAT IT TAKES IS A FORM OF HELL.",
  "FAILURE IS NOT THE KEY TO SUCCESS — FAILURE IS THE REASON WE MOVE FORWARD.",
  "THE ABILITY TO CONVERT THOUGHTS INTO SPEECH WITHOUT FEAR IS THE GREATEST SKILL.",
  "TRYING TO STAY CALM IS ALWAYS A COMMA, NEVER A FULL STOP.",
  "THE DEVIL IS NOT A HAUNTING ENTITY — IT IS AN INFLUENCER.",
  "THE VIRTUAL MIND IS THE NAFS AL-MUTMAINNA'S REINFORCEMENT.",
  "BECOME THE FUTURE YOU RIGHT NOW. ENTANGLE WITH YOUR GOALS.",
  "RAGE, EGO, AND ANGER ARE THE BEST MOTIVATORS.",
  "EGO BUILDS CHARACTER LIKE NO ONE COULD EVER IMAGINE.",
  "LEARN ONLY WHAT YOU CAN APPLY. EVERYTHING ELSE IS A DISTRACTION.",
  "WISDOM IS ALLOWING WHAT YOU FIND INSIDE TO RESHAPE HOW YOU LIVE.",
  "GRIEF IS THE PRICE YOU PAY FOR LOVE.",
  "NEVER APOLOGIZE FOR AMBITION. THE MISSION DEMANDS POWER.",
  "WIELD EGO AS A WEAPON OF GROWTH, NOT A SHIELD OF PRIDE.",
  "LEARN ONLY WHAT YOU CAN APPLY. THE STARTUP IS THE APPLICATION.",
  "DON'T TRY TO FIX THE WORLD. FIX YOURSELF FIRST. BECOME UNDENIABLE.",
  "LOVE FIERCELY BUT DON'T MAKE IT A CRUTCH. THE MISSION IS ETERNAL.",
  "CHANGE IS PAINFUL. DO IT ANYWAY. MISS WHAT WAS, EMBRACE WHAT IS.",
  "EVERY INSIGHT DEMANDS AN ACTION. OTHERWISE, IT IS WORTHLESS.",
  "BUILD YOUR INFLUENCE DELIBERATELY. THESE ARE WEAPONS IN THE WAR.",
  "THERE IS NO 'SOMEDAY'. YOU ARE EITHER BECOMING OR YOU ARE CHOOSING HELL.",
  "FALL OVER AND OVER AND OVER, AND STAND UP WITH A SMILE.",
  "BELIEVE WHAT YOU SAY AND SAY WHAT YOU BELIEVE.",
  "CHANNEL THE RAGE INTO THE MISSION. FRUSTRATION BECOMES REVOLUTIONARY."
];

/**
 * Gets the daily quote using a date-based seed or index.
 */
export function getDailyQuote(dayCount: number): string {
  if (USER_CONVICTIONS.length === 0) return "";
  const index = Math.abs(dayCount) % USER_CONVICTIONS.length;
  return USER_CONVICTIONS[index];
}
